auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

schema_config:
  configs:
    - from: 2024-02-07
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache

limits_config:
  allow_structured_metadata: false
  retention_period: 7d
  max_query_length: 720h
  max_query_parallelism: 32
  max_entries_limit_per_query: 5000

compactor:
  working_directory: /loki/compactor

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
